### ISSUE TITLE
Error: Could not figure out current Linux distro

### ISSUE THREAD

**Issue by Beetix** [mongodb-js/runner#196]
Hi,

I have tried to run `mongodb-runner start` (version 4.8.3) but I am getting an error:
```
Starting a MongoDB deployment to test against...Error: Could not figure out current Linux distro (Arch, arch)
    at Object.getCurrentLinuxDistro (/usr/lib/node_modules/mongodb-runner/node_modules/mongodb-download-url/lib/linux-distro.js:66:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async parseTarget (/usr/lib/node_modules/mongodb-runner/node_modules/mongodb-download-url/lib/index.js:73:29)
    at async options (/usr/lib/node_modules/mongodb-runner/node_modules/mongodb-download-url/lib/index.js:239:31)
    at async getDownloadURL (/usr/lib/node_modules/mongodb-runner/node_modules/mongodb-download-url/lib/index.js:243:27)
```
I am running Arch Linux on x86 which seems recognised from Node.js's console:
```
Welcome to Node.js v16.13.1.
Type ".help" for more information.
> process.platform
'linux'
> process.arch
'x64'
```
Do you have an idea of why I am getting this error?

Thank you

**Comment by Aidan-Eves** [comment]
I'm running into the same problem, i'm currently running EndeavourOS and i get the same output.

**Comment by JBLeap** [comment]
Same problem in ManjaroLinux

**Comment by TravisLeeRichardson** [comment]
same problem with pop_os!

I believe the issue is that only a certain set of linux distros are mapped.  In this linux-distro.js file, for instance, you can see Ubuntu, Debian, etc, but no support for the other distros mentioned in this thread...

![image](https://github.com/mongodb-js/runner/assets/106935903/8a49ab99-c4c9-44eb-a23a-9f88d3becbb5)
