### ISSUE TITLE
Bug after installing new version: "figures is not defined"

### ISSUE THREAD

**Issue by rueckstiess** [mongodb-js/runner#29]
```
$ m use 3.1.8
  Downloading MongoDB v3.1.8 [========================================] 100% 0.0sec
/usr/local/lib/node_modules/mongodb-version-manager/lib/download.js:52
        console.log(chalk.bold.green(figures.tick),
                                     ^
ReferenceError: figures is not defined
    at WriteStream.onFinish (/usr/local/lib/node_modules/mongodb-version-manager/lib/download.js:52:38)
    at WriteStream.g (events.js:199:16)
    at WriteStream.emit (events.js:129:20)
    at finishMaybe (_stream_writable.js:484:14)
    at afterWrite (_stream_writable.js:362:3)
    at onwrite (_stream_writable.js:352:7)
    at WritableState.onwrite (_stream_writable.js:105:5)
    at fs.js:1799:5
    at FSReqWrap.strWrapper (fs.js:568:5)
```

**Comment by imlucas** [comment]
fixed in mongodb-version-manager@0.8.7
